# Generated by Django 3.2.12 on 2022-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=1645426513, verbose_name='创建时间')),
                ('updated_at', models.IntegerField(default=1645426513, verbose_name='修改时间')),
                ('format_created_at', models.DateTimeField(auto_now=True, verbose_name='格式化时间')),
                ('format_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='格式化修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'db_table': 'test_web',
            },
        ),
    ]
